set -xe
BRANCH=$BRANCH


source .properties/$BRANCH.properties

APP_BASE_IMAGE_REPO=$APP_BASE_IMAGE_REPO
APP_BASE_IMAGE_TAG=$APP_BASE_IMAGE_TAG

APP_BASE_IMAGE_REPO_TAG=$APP_BASE_IMAGE_REPO:$APP_BASE_IMAGE_TAG

APP_IMAGE_REPO=$APP_IMAGE_REPO
APP_IMAGE_TAG=$APP_IMAGE_TAG

APP_IMAGE_REPO_TAG=$APP_IMAGE_REPO:$APP_IMAGE_TAG

docker images | grep $APP_BASE_IMAGE_REPO_TAG 

docker pull $APP_BASE_IMAGE_REPO_TAG


docker build --network=host -t $APP_IMAGE_REPO_TAG \
    --build-arg APP_BASE_IMAGE_REPO_TAG=$APP_BASE_IMAGE_REPO_TAG \
    --build-arg SERVICE_ENV=$BRANCH \
    --build-arg SERVICE_IMAGE=$APP_IMAGE_REPO_TAG \
    . -f Dockerfile
