ARG APP_BASE_IMAGE_REPO_TAG
FROM ${APP_BASE_IMAGE_REPO_TAG}
ARG SERVICE_ENV
ARG SERVICE_IMAGE

WORKDIR /workspace

ENV SERVICE_ENV=${SERVICE_ENV}
ENV SERVICE_IMAGE=${SERVICE_IMAGE}

COPY kind_parser /workspace/

